import type { Locale } from "@/lib/i18n";

export const aboutAsideContent = {
  en: ["SaaS + solution, built as one operating system for product work.", "Strategy, interface, engineering, automation, deployment, and support are treated as one responsibility."],
  nl: ["SaaS + oplossing, gebouwd als een besturingssysteem voor productwerk.", "Strategie, interface, engineering, automatisering, deployment en support worden als een verantwoordelijkheid behandeld."],
  de: ["SaaS + Loesung, gebaut wie ein Betriebssystem fuer Produktarbeit.", "Strategie, Interface, Engineering, Automatisierung, Deployment und Support werden als eine Verantwortung behandelt."],
  es: ["SaaS + solucion, construido como un sistema operativo para trabajo de producto.", "Estrategia, interfaz, ingenieria, automatizacion, despliegue y soporte se tratan como una sola responsabilidad."]
} satisfies Record<Locale, string[]>;

export const missionVisionLocalized = {
  en: {
    label: "- Mission & Vision",
    navCta: "Contact us",
    heroTitle: "One partner for the systems, risks, processes, and surprises that stand between you and progress.",
    heroBody: "SaaSolution was built for clients who do not want a stack of vendors, tickets, meetings, and half-owned responsibilities. With 23 years of hardware, software, security, and process knowledge behind our work, we look at the full operating reality.",
    promiseTitle: "Our mission",
    promiseBody: "Our mission is to be the practical technology partner that helps organizations solve problems from the inside and the outside at the same time.",
    visionTitle: "Our vision",
    visionBody: "Our vision is a world where companies do not need to choose between speed, security, reliability, and imagination.",
    founderTitle: "Built on 23 years of cross-domain experience",
    founderBody: "Real business trouble rarely lives in one box. A software issue may be a process issue. A security concern may be a people issue. A hardware limitation may be a product strategy issue.",
    pillarsTitle: "How we become the only partner you need",
    pillars: [["Hardware to cloud", "We reason from devices through APIs, dashboards, infrastructure, and support operations."], ["Security by design", "Security is part of architecture and process, not a final checklist."], ["Process clarity", "We map how work really moves and remove friction with software and automation."], ["Product execution", "We design, build, deploy, and improve practical systems."], ["Inside the box", "We respect constraints, budgets, compliance, legacy systems, and daily reality."], ["Outside the box", "We challenge assumptions when a better path needs a new workflow or interface."]],
    closingTitle: "The result: fewer handoffs, fewer blind spots, more ownership.",
    closingBody: "We ask what needs to stop breaking, what needs to become simpler, what risk needs to disappear, and what future capability the organization should gain.",
    ctaButton: "Start the conversation",
    topCards: [["Hardware", "Connected thinking"], ["Software", "Connected thinking"], ["Security", "Connected thinking"]]
  },
  nl: {
    label: "- Missie & visie",
    navCta: "Contact opnemen",
    heroTitle: "Een partner voor de systemen, risico's, processen en verrassingen die tussen jou en vooruitgang staan.",
    heroBody: "SaaSolution is gebouwd voor klanten die geen stapel leveranciers, tickets, meetings en half eigenaarschap willen. Met 23 jaar kennis van hardware, software, beveiliging en processen kijken we naar de volledige operationele realiteit.",
    promiseTitle: "Onze missie",
    promiseBody: "Onze missie is om de praktische technologiepartner te zijn die organisaties helpt problemen van binnenuit en van buitenaf tegelijk op te lossen.",
    visionTitle: "Onze visie",
    visionBody: "Onze visie is een wereld waarin bedrijven niet hoeven te kiezen tussen snelheid, beveiliging, betrouwbaarheid en verbeelding.",
    founderTitle: "Gebouwd op 23 jaar domeinoverschrijdende ervaring",
    founderBody: "Echte bedrijfsproblemen zitten zelden in een vakje. Een softwareprobleem kan een procesprobleem zijn. Een beveiligingsvraag kan een mensenvraag zijn. Een hardwarebeperking kan productstrategie raken.",
    pillarsTitle: "Hoe we de enige partner worden die je nodig hebt",
    pillars: [["Van hardware tot cloud", "We denken van apparaten tot APIs, dashboards, infrastructuur en supportoperaties."], ["Beveiliging vanaf ontwerp", "Beveiliging hoort in architectuur en proces, niet pas in een laatste checklist."], ["Proceshelderheid", "We brengen in kaart hoe werk echt beweegt en halen frictie weg met software en automatisering."], ["Productuitvoering", "We ontwerpen, bouwen, deployen en verbeteren praktische systemen."], ["Binnen de kaders", "We respecteren beperkingen, budgetten, compliance, legacy-systemen en dagelijkse realiteit."], ["Buiten de kaders", "We dagen aannames uit wanneer een betere route een nieuwe workflow of interface nodig heeft."]],
    closingTitle: "Het resultaat: minder overdrachten, minder blinde vlekken, meer eigenaarschap.",
    closingBody: "We vragen wat moet stoppen met breken, wat eenvoudiger moet worden, welk risico moet verdwijnen en welke toekomstige capaciteit de organisatie moet krijgen.",
    ctaButton: "Start het gesprek",
    topCards: [["Hardware", "Verbonden denken"], ["Software", "Verbonden denken"], ["Beveiliging", "Verbonden denken"]]
  },
  de: {
    label: "- Mission und Vision",
    navCta: "Kontakt aufnehmen",
    heroTitle: "Ein Partner fuer Systeme, Risiken, Prozesse und Ueberraschungen, die zwischen Ihnen und Fortschritt stehen.",
    heroBody: "SaaSolution ist fuer Kunden gebaut, die keine Sammlung von Anbietern, Tickets, Meetings und halber Verantwortung wollen. Mit 23 Jahren Erfahrung in Hardware, Software, Sicherheit und Prozessen betrachten wir die gesamte operative Realitaet.",
    promiseTitle: "Unsere Mission",
    promiseBody: "Unsere Mission ist es, der praktische Technologiepartner zu sein, der Organisationen hilft, Probleme von innen und aussen zugleich zu loesen.",
    visionTitle: "Unsere Vision",
    visionBody: "Unsere Vision ist eine Welt, in der Unternehmen nicht zwischen Geschwindigkeit, Sicherheit, Zuverlaessigkeit und Vorstellungskraft waehlen muessen.",
    founderTitle: "Gebaut auf 23 Jahren domänenuebergreifender Erfahrung",
    founderBody: "Echte Geschaeftsprobleme leben selten in einem Feld. Ein Softwareproblem kann ein Prozessproblem sein. Eine Sicherheitsfrage kann eine Menschenfrage sein. Eine Hardwaregrenze kann Produktstrategie betreffen.",
    pillarsTitle: "Wie wir der einzige Partner werden, den Sie brauchen",
    pillars: [["Von Hardware bis Cloud", "Wir denken von Geraeten bis APIs, Dashboards, Infrastruktur und Supportprozessen."], ["Sicherheit ab Entwurf", "Sicherheit gehoert in Architektur und Prozess, nicht erst in eine letzte Checkliste."], ["Prozessklarheit", "Wir zeigen, wie Arbeit wirklich fliesst, und entfernen Reibung mit Software und Automatisierung."], ["Produktausfuehrung", "Wir entwerfen, bauen, deployen und verbessern praktische Systeme."], ["Innerhalb der Rahmen", "Wir respektieren Grenzen, Budgets, Compliance, Legacy-Systeme und Alltagsrealitaet."], ["Ausserhalb der Rahmen", "Wir hinterfragen Annahmen, wenn ein besserer Weg neue Workflows oder Interfaces braucht."]],
    closingTitle: "Das Ergebnis: weniger Uebergaben, weniger blinde Flecken, mehr Verantwortung.",
    closingBody: "Wir fragen, was aufhoeren muss zu brechen, was einfacher werden muss, welches Risiko verschwinden soll und welche Faehigkeit die Organisation gewinnen soll.",
    ctaButton: "Gespraech starten",
    topCards: [["Hardware", "Verbundenes Denken"], ["Software", "Verbundenes Denken"], ["Sicherheit", "Verbundenes Denken"]]
  },
  es: {
    label: "- Mision y vision",
    navCta: "Contactar",
    heroTitle: "Un partner para los sistemas, riesgos, procesos y sorpresas que frenan tu avance.",
    heroBody: "SaaSolution fue creada para clientes que no quieren una pila de proveedores, tickets, reuniones y responsabilidades a medias. Con 23 anos de conocimiento en hardware, software, seguridad y procesos, miramos toda la realidad operativa.",
    promiseTitle: "Nuestra mision",
    promiseBody: "Nuestra mision es ser el partner tecnologico practico que ayuda a resolver problemas desde dentro y desde fuera al mismo tiempo.",
    visionTitle: "Nuestra vision",
    visionBody: "Nuestra vision es un mundo donde las empresas no tengan que elegir entre velocidad, seguridad, fiabilidad e imaginacion.",
    founderTitle: "Construido sobre 23 anos de experiencia transversal",
    founderBody: "Los problemas reales rara vez viven en una sola caja. Un problema de software puede ser de proceso. Una duda de seguridad puede ser de personas. Una limitacion de hardware puede tocar estrategia de producto.",
    pillarsTitle: "Como nos convertimos en el unico partner que necesitas",
    pillars: [["De hardware a cloud", "Razonamos desde dispositivos hasta APIs, dashboards, infraestructura y soporte."], ["Seguridad desde el diseno", "La seguridad forma parte de arquitectura y proceso, no de una lista final."], ["Claridad de procesos", "Mapeamos como se mueve realmente el trabajo y quitamos friccion con software y automatizacion."], ["Ejecucion de producto", "Disenamos, construimos, desplegamos y mejoramos sistemas practicos."], ["Dentro del marco", "Respetamos limites, presupuestos, compliance, legacy y realidad diaria."], ["Fuera del marco", "Cuestionamos supuestos cuando un mejor camino necesita nuevo flujo o interfaz."]],
    closingTitle: "Resultado: menos traspasos, menos puntos ciegos, mas responsabilidad.",
    closingBody: "Preguntamos que debe dejar de romperse, que debe simplificarse, que riesgo debe desaparecer y que capacidad futura debe ganar la organizacion.",
    ctaButton: "Empezar conversacion",
    topCards: [["Hardware", "Pensamiento conectado"], ["Software", "Pensamiento conectado"], ["Seguridad", "Pensamiento conectado"]]
  }
} satisfies Record<Locale, Record<string, string | string[][]>>;

export const blogContent = {
  en: {
    ask: "Ask for access", label: "- Project Pulse", title: "A fun project blog clients can check without chasing anyone.", intro: "Project Pulse turns support conversations, team notes, and AI-assisted summaries into clear, client-friendly updates. Clients get the feeling that work is alive, moving, and handled by real people.", status: "Live-style status", stats: ["updates this week", "support-sourced posts", "active project streams"], feed: "Public feed", feedTitle: "What clients see.", feedBody: "Updates are written like short field notes: human, useful, a little playful, and careful about privacy. No internal secrets, no noisy ticket dumps.", joy: "Project joy, visible progress", joyTitle: "Clients stay updated while we have fun building.", joyBody: "Project Pulse is built for quick, useful updates about what was done, improved, or shipped. We do not ask for approval on every normal progress post, but we never publish private client information, sensitive details, or identifying material without approval.",
    updates: [["First Line AI", "Training the support handoff flow", "AI draft from support notes", "Today, 14:20", "Good momentum", "We connected the latest support categories to the agent routing logic and tested the friendly handoff message. The next pass focuses on mixed billing and technical questions."], ["Smart NFC Guest Pass", "Door access test passed in staging", "Team update", "Yesterday, 17:45", "Hardware behaving", "The NFC scan flow now writes a clean activity trail and the dashboard shows who entered, when, and through which pass."], ["Mithaq", "Document review queue is calmer now", "Support conversation", "Monday, 09:10", "Less friction", "We simplified review status labels so clients can see what is waiting on them and what is already with the team."]]
  },
  nl: {
    ask: "Toegang vragen", label: "- Project Pulse", title: "Een leuke projectblog die klanten kunnen bekijken zonder achter iemand aan te gaan.", intro: "Project Pulse maakt van supportgesprekken, teamnotities en AI-samenvattingen heldere updates voor klanten. Klanten voelen dat het werk leeft, beweegt en door echte mensen wordt opgepakt.", status: "Live-achtige status", stats: ["updates deze week", "posts uit support", "actieve projectstromen"], feed: "Openbare feed", feedTitle: "Wat klanten zien.", feedBody: "Updates lezen als korte veldnotities: menselijk, nuttig, een beetje speels en zorgvuldig met privacy. Geen interne geheimen, geen ticketruis.", joy: "Projectplezier, zichtbare voortgang", joyTitle: "Klanten blijven op de hoogte terwijl wij met plezier bouwen.", joyBody: "Project Pulse is gemaakt voor snelle, nuttige updates over wat is gedaan, verbeterd of gelanceerd. We vragen niet voor elke normale voortgangspost toestemming, maar publiceren nooit prive klantinformatie, gevoelige details of herleidbare informatie zonder goedkeuring.",
    updates: [["First Line AI", "Support-overdracht trainen", "AI-concept uit supportnotities", "Vandaag, 14:20", "Goede vaart", "We hebben de nieuwste supportcategorieen gekoppeld aan de agent-routing en het vriendelijke overdrachtsbericht getest. De volgende ronde focust op gemengde billing- en technische vragen."], ["Smart NFC Guest Pass", "Toegangstest geslaagd in staging", "Teamupdate", "Gisteren, 17:45", "Hardware werkt mee", "De NFC-scanflow schrijft nu een nette activiteitengeschiedenis en het dashboard toont wie binnenkwam, wanneer en via welke pas."], ["Mithaq", "Documentreview voelt rustiger", "Supportgesprek", "Maandag, 09:10", "Minder frictie", "We hebben reviewstatussen eenvoudiger gemaakt zodat klanten zien wat op hen wacht en wat al bij het team ligt."]]
  },
  de: {
    ask: "Zugang anfragen", label: "- Project Pulse", title: "Ein lockerer Projektblog, den Kunden ansehen koennen, ohne nachzufragen.", intro: "Project Pulse macht aus Supportgespraechen, Teamnotizen und KI-Zusammenfassungen klare, kundenfreundliche Updates. Kunden sehen, dass die Arbeit lebt, vorangeht und von echten Menschen betreut wird.", status: "Live-aehnlicher Status", stats: ["Updates diese Woche", "Posts aus Support", "aktive Projektstreams"], feed: "Oeffentlicher Feed", feedTitle: "Was Kunden sehen.", feedBody: "Updates lesen sich wie kurze Feldnotizen: menschlich, nuetzlich, etwas spielerisch und achtsam mit Datenschutz. Keine internen Geheimnisse, kein Ticketlaerm.", joy: "Projektfreude, sichtbarer Fortschritt", joyTitle: "Kunden bleiben informiert, waehrend wir mit Freude bauen.", joyBody: "Project Pulse ist fuer schnelle, nuetzliche Updates gedacht: was erledigt, verbessert oder ausgeliefert wurde. Wir fragen nicht fuer jeden normalen Fortschrittspost um Freigabe, veroeffentlichen aber keine privaten Kundendaten, sensiblen Details oder identifizierenden Informationen ohne Zustimmung.",
    updates: [["First Line AI", "Support-Uebergabe trainieren", "KI-Entwurf aus Supportnotizen", "Heute, 14:20", "Guter Schwung", "Wir haben neue Supportkategorien mit der Agent-Routinglogik verbunden und die freundliche Uebergabenachricht getestet. Die naechste Runde fokussiert gemischte Billing- und Technikfragen."], ["Smart NFC Guest Pass", "Zugangstest in Staging bestanden", "Teamupdate", "Gestern, 17:45", "Hardware spielt mit", "Der NFC-Scan schreibt nun eine saubere Aktivitaetsspur und das Dashboard zeigt, wer wann mit welchem Pass eingetreten ist."], ["Mithaq", "Dokumentenreview ist ruhiger", "Supportgespraech", "Montag, 09:10", "Weniger Reibung", "Wir haben Review-Status vereinfacht, damit Kunden sehen, was auf sie wartet und was bereits beim Team liegt."]]
  },
  es: {
    ask: "Pedir acceso", label: "- Project Pulse", title: "Un blog de proyecto divertido que los clientes pueden mirar sin perseguir a nadie.", intro: "Project Pulse convierte conversaciones de soporte, notas del equipo y resumenes con AI en actualizaciones claras para clientes. Los clientes sienten que el trabajo esta vivo, avanza y lo llevan personas reales.", status: "Estado tipo live", stats: ["updates esta semana", "posts desde soporte", "flujos activos"], feed: "Feed publico", feedTitle: "Lo que ven los clientes.", feedBody: "Las updates son notas breves: humanas, utiles, un poco divertidas y cuidadosas con la privacidad. Sin secretos internos ni ruido de tickets.", joy: "Alegria de proyecto, progreso visible", joyTitle: "Los clientes se mantienen informados mientras disfrutamos construyendo.", joyBody: "Project Pulse esta pensado para updates rapidas sobre lo hecho, mejorado o lanzado. No pedimos aprobacion para cada update normal, pero nunca publicamos informacion privada, sensible o identificable del cliente sin aprobacion.",
    updates: [["First Line AI", "Entrenando el flujo de traspaso de soporte", "Borrador AI desde notas de soporte", "Hoy, 14:20", "Buen ritmo", "Conectamos las nuevas categorias de soporte a la logica de routing del agente y probamos el mensaje de traspaso amigable. La proxima ronda trata preguntas mixtas de billing y tecnica."], ["Smart NFC Guest Pass", "Prueba de acceso superada en staging", "Update del equipo", "Ayer, 17:45", "Hardware colaborando", "El flujo NFC ahora deja una actividad limpia y el dashboard muestra quien entro, cuando y con que pase."], ["Mithaq", "La cola de revision esta mas tranquila", "Conversacion de soporte", "Lunes, 09:10", "Menos friccion", "Simplificamos los estados de revision para que los clientes vean que espera de ellos y que ya esta con el equipo."]]
  }
} satisfies Record<Locale, Record<string, string | string[] | string[][]>>;

export const helpCenterContent = {
  en: {
    nav: "Human guidance", label: "- Help Center", supportLabel: "Support", contactLabel: "Contact", title: "Find the right answer, or the right human.", intro: "Start with the most common questions. If your situation needs investigation, go to Support. If it needs judgement, context, or personal guidance, contact us directly.", path: "Choose the fastest path", faq: "FAQ", faqTitle: "Logical questions, simple routes.", faqIntro: "These answers reduce waiting. When the answer depends on your setup, we point you to the right place for human help.", unsure: "Still unsure?", unsureTitle: "If the question needs a person, do not wrestle with it alone.", unsureBody: "Support is best for operational issues. Contact is best for guidance, planning, partnerships, sensitive topics, or anything where the human context matters.",
    routes: [["Need an answer", "Start here in the Help Center.", "/help-center", "You are here"], ["Something is broken", "Open a support request.", "https://saasupport.com", "Support"], ["Need human guidance", "Talk to the team directly.", "/contact", "Contact"], ["Want project progress", "Read client-friendly updates.", "/blog", "Project Pulse"]],
    featured: [["Where can I see project progress?", "Use Project Pulse to follow approved updates and recent improvements.", "/blog", "Open Project Pulse"], ["I have a technical issue. Where should I go?", "Use Support when something is broken, blocked, or needs investigation.", "https://saasupport.com", "Go to support"], ["I need advice from a person.", "Use Contact when your question needs human guidance or context.", "/contact", "Contact us"]],
    groups: [["Projects & Updates", "How do I know if my project is being worked on?", "Check Project Pulse for short updates about what was done, improved, or shipped.", "Will every internal task appear on the blog?", "No. We only share updates that are useful for clients.", "Can I ask for a deeper project status?", "Yes. Use Support for delivery questions or Contact for broader direction."], ["Support", "When should I use Support?", "Use Support for bugs, login issues, access problems, broken workflows, missing data, urgent blockers, or investigation.", "What should I include?", "Include product name, expected result, actual result, screenshots, device details, and whether it blocks work.", "How urgent is my request?", "If your team cannot continue, mark urgent. Otherwise normal priority is best."], ["Contact & Human Guidance", "When should I use Contact instead of Support?", "Use Contact for strategy, new projects, contracts, partnerships, security concerns, or context-heavy decisions.", "Can I attach files?", "Yes. Use the attachment field on Contact and attach the file before sending.", "Who will reply?", "Your message is routed to client operations, a technical lead, or the founder depending on topic."], ["Security & Privacy", "Will SaaSolution publish client information?", "No private client information, sensitive details, or identifying material is published without approval.", "Can I send security questions through the website?", "Use Contact for general questions and Support for active incidents.", "Do project updates include technical secrets?", "No. Project Pulse shows progress without credentials, architecture secrets, vulnerabilities, or private business context."]]
  },
  nl: {
    nav: "Menselijke hulp", label: "- Helpcentrum", supportLabel: "Support", contactLabel: "Contact", title: "Vind het juiste antwoord, of de juiste persoon.", intro: "Begin met de meest voorkomende vragen. Als je situatie onderzoek nodig heeft, ga naar Support. Als er oordeel, context of persoonlijke begeleiding nodig is, neem contact met ons op.", path: "Kies de snelste route", faq: "FAQ", faqTitle: "Logische vragen, simpele routes.", faqIntro: "Deze antwoorden verminderen wachttijd. Als het antwoord afhangt van jouw setup, wijzen we je naar de juiste hulp.", unsure: "Nog niet zeker?", unsureTitle: "Als de vraag een persoon nodig heeft, hoef je er niet alleen mee te worstelen.", unsureBody: "Support is het beste voor operationele issues. Contact is het beste voor begeleiding, planning, partnerships, gevoelige onderwerpen of vragen waar menselijke context telt.",
    routes: [["Antwoord nodig", "Begin hier in het helpcentrum.", "/help-center", "Je bent hier"], ["Iets is kapot", "Open een supportverzoek.", "https://saasupport.com", "Support"], ["Menselijke hulp nodig", "Praat direct met het team.", "/contact", "Contact"], ["Projectvoortgang zien", "Lees klantvriendelijke updates.", "/blog", "Project Pulse"]],
    featured: [["Waar zie ik projectvoortgang?", "Gebruik Project Pulse voor goedgekeurde updates en recente verbeteringen.", "/blog", "Open Project Pulse"], ["Ik heb een technisch probleem. Waar moet ik heen?", "Gebruik Support wanneer iets kapot is, blokkeert of onderzoek nodig heeft.", "https://saasupport.com", "Naar support"], ["Ik heb advies van een persoon nodig.", "Gebruik Contact wanneer je vraag menselijke begeleiding of context nodig heeft.", "/contact", "Contact opnemen"]],
    groups: [["Projecten & updates", "Hoe weet ik of er aan mijn project wordt gewerkt?", "Bekijk Project Pulse voor korte updates over wat is gedaan, verbeterd of gelanceerd.", "Komt elke interne taak op de blog?", "Nee. We delen alleen updates die nuttig zijn voor klanten.", "Kan ik een diepere status vragen?", "Ja. Gebruik Support voor oplevervragen of Contact voor bredere richting."], ["Support", "Wanneer gebruik ik Support?", "Gebruik Support voor bugs, loginproblemen, toegangsproblemen, kapotte workflows, ontbrekende data, urgente blokkades of onderzoek.", "Wat moet ik meesturen?", "Vermeld productnaam, verwacht resultaat, werkelijk resultaat, screenshots, apparaatgegevens en of het werk blokkeert.", "Hoe urgent is mijn verzoek?", "Als je team niet verder kan, markeer urgent. Anders is normale prioriteit meestal beter."], ["Contact & menselijke begeleiding", "Wanneer gebruik ik Contact in plaats van Support?", "Gebruik Contact voor strategie, nieuwe projecten, contracten, partnerships, beveiligingsvragen of besluiten met veel context.", "Kan ik bestanden toevoegen?", "Ja. Gebruik het bijlageveld op Contact en voeg het bestand toe voordat je verzendt.", "Wie reageert?", "Je bericht gaat naar klantoperaties, een technisch lead of de oprichter afhankelijk van het onderwerp."], ["Beveiliging & privacy", "Publiceert SaaSolution klantinformatie?", "Nee. Prive klantinformatie, gevoelige details of herleidbare informatie worden niet zonder goedkeuring gepubliceerd.", "Kan ik beveiligingsvragen via de site sturen?", "Gebruik Contact voor algemene vragen en Support voor actieve incidenten.", "Bevatten projectupdates technische geheimen?", "Nee. Project Pulse toont voortgang zonder inloggegevens, architectuurgeheimen, kwetsbaarheden of private bedrijfscontext."]]
  },
  de: {
    nav: "Menschliche Hilfe", label: "- Hilfezentrum", supportLabel: "Support", contactLabel: "Kontakt", title: "Finden Sie die richtige Antwort, oder die richtige Person.", intro: "Beginnen Sie mit den haeufigsten Fragen. Wenn Ihre Situation Untersuchung braucht, gehen Sie zu Support. Wenn Urteil, Kontext oder persoenliche Hilfe noetig ist, kontaktieren Sie uns.", path: "Den schnellsten Weg waehlen", faq: "FAQ", faqTitle: "Logische Fragen, einfache Wege.", faqIntro: "Diese Antworten reduzieren Wartezeit. Wenn die Antwort von Ihrem Setup abhaengt, zeigen wir den richtigen Weg.", unsure: "Noch unsicher?", unsureTitle: "Wenn die Frage einen Menschen braucht, muessen Sie nicht allein damit ringen.", unsureBody: "Support ist fuer operative Probleme am besten. Kontakt ist fuer Beratung, Planung, Partnerschaften, sensible Themen oder Kontextfragen am besten.",
    routes: [["Antwort gesucht", "Starten Sie im Hilfezentrum.", "/help-center", "Sie sind hier"], ["Etwas ist kaputt", "Supportanfrage oeffnen.", "https://saasupport.com", "Support"], ["Menschliche Hilfe", "Direkt mit dem Team sprechen.", "/contact", "Kontakt"], ["Projektfortschritt", "Kundenfreundliche Updates lesen.", "/blog", "Project Pulse"]],
    featured: [["Wo sehe ich Projektfortschritt?", "Nutzen Sie Project Pulse fuer freigegebene Updates und Verbesserungen.", "/blog", "Project Pulse oeffnen"], ["Ich habe ein technisches Problem. Wohin?", "Nutzen Sie Support, wenn etwas kaputt ist, blockiert oder untersucht werden muss.", "https://saasupport.com", "Zu Support"], ["Ich brauche Rat von einer Person.", "Nutzen Sie Kontakt, wenn Ihre Frage menschliche Hilfe oder Kontext braucht.", "/contact", "Kontakt aufnehmen"]],
    groups: [["Projekte & Updates", "Woher weiss ich, ob an meinem Projekt gearbeitet wird?", "Pruefen Sie Project Pulse fuer kurze Updates ueber erledigte, verbesserte oder gelieferte Arbeit.", "Erscheint jede interne Aufgabe im Blog?", "Nein. Wir teilen nur Updates, die fuer Kunden nuetzlich sind.", "Kann ich einen tieferen Status anfragen?", "Ja. Nutzen Sie Support fuer Lieferfragen oder Kontakt fuer die groessere Richtung."], ["Support", "Wann nutze ich Support?", "Nutzen Sie Support fuer Bugs, Loginprobleme, Zugriffsprobleme, defekte Workflows, fehlende Daten, Blocker oder Untersuchungen.", "Was soll ich mitschicken?", "Produktname, Erwartung, Ergebnis, Screenshots, Geraetedaten und ob es Arbeit blockiert.", "Wie dringend ist es?", "Wenn Ihr Team nicht weiterarbeiten kann, markieren Sie dringend. Sonst ist normale Prioritaet meist besser."], ["Kontakt & menschliche Hilfe", "Wann Kontakt statt Support?", "Fuer Strategie, neue Projekte, Vertraege, Partnerschaften, Sicherheitsfragen oder kontextreiche Entscheidungen.", "Kann ich Dateien anhaengen?", "Ja. Nutzen Sie das Anhangfeld auf Kontakt und fuegen Sie die Datei vor dem Senden hinzu.", "Wer antwortet?", "Je nach Thema Kundenoperationen, technischer Lead oder Gruender."], ["Sicherheit & Datenschutz", "Veroeffentlicht SaaSolution Kundendaten?", "Nein. Private Kundendaten, sensible Details oder identifizierende Informationen werden nicht ohne Freigabe veroeffentlicht.", "Kann ich Sicherheitsfragen senden?", "Nutzen Sie Kontakt fuer allgemeine Fragen und Support fuer aktive Vorfaelle.", "Enthalten Projektupdates technische Geheimnisse?", "Nein. Project Pulse zeigt Fortschritt ohne Zugangsdaten, Architekturgeheimnisse, Schwachstellen oder privaten Geschaeftskontext."]]
  },
  es: {
    nav: "Ayuda humana", label: "- Centro de ayuda", supportLabel: "Soporte", contactLabel: "Contacto", title: "Encuentra la respuesta correcta, o la persona correcta.", intro: "Empieza con las preguntas comunes. Si tu situacion requiere investigacion, ve a soporte. Si necesita criterio, contexto o guia personal, contactanos.", path: "Elige la ruta mas rapida", faq: "FAQ", faqTitle: "Preguntas logicas, rutas simples.", faqIntro: "Estas respuestas reducen espera. Si depende de tu setup, te mandamos al lugar correcto.", unsure: "Aun con dudas?", unsureTitle: "Si la pregunta necesita una persona, no la pelees solo.", unsureBody: "Soporte es mejor para problemas operativos. Contacto es mejor para guia, planificacion, partners, temas sensibles o contexto humano.",
    routes: [["Necesito respuesta", "Empieza en el centro de ayuda.", "/help-center", "Estas aqui"], ["Algo esta roto", "Abre soporte.", "https://saasupport.com", "Soporte"], ["Necesito guia humana", "Habla con el equipo.", "/contact", "Contacto"], ["Ver progreso", "Lee updates para clientes.", "/blog", "Project Pulse"]],
    featured: [["Donde veo el progreso?", "Usa Project Pulse para updates aprobadas y mejoras recientes.", "/blog", "Abrir Project Pulse"], ["Tengo un problema tecnico. Donde voy?", "Usa soporte cuando algo esta roto, bloqueado o necesita investigacion.", "https://saasupport.com", "Ir a soporte"], ["Necesito consejo de una persona.", "Usa contacto cuando tu pregunta necesita guia humana o contexto.", "/contact", "Contactar"]],
    groups: [["Proyectos & updates", "Como se si trabajan en mi proyecto?", "Revisa Project Pulse para updates cortas sobre lo hecho, mejorado o lanzado.", "Sale cada tarea interna en el blog?", "No. Solo compartimos updates utiles para clientes.", "Puedo pedir mas detalle?", "Si. Usa soporte para preguntas de entrega o contacto para direccion general."], ["Soporte", "Cuando uso soporte?", "Para bugs, login, accesos, workflows rotos, datos faltantes, bloqueos urgentes o investigacion.", "Que incluyo?", "Producto, resultado esperado, resultado real, capturas, dispositivo y si bloquea trabajo.", "Que tan urgente es?", "Si tu equipo no puede seguir, marca urgente. Si no, prioridad normal suele ser mejor."], ["Contacto y guia humana", "Cuando uso contacto?", "Para estrategia, nuevos proyectos, contratos, partners, seguridad o decisiones con contexto.", "Puedo adjuntar archivos?", "Si. Usa el campo de adjunto en contacto y adjunta antes de enviar.", "Quien responde?", "Segun tema: operaciones de cliente, lead tecnico o fundador."], ["Seguridad & privacidad", "SaaSolution publica informacion de clientes?", "No. Informacion privada, sensible o identificable no se publica sin aprobacion.", "Puedo enviar preguntas de seguridad?", "Usa contacto para preguntas generales y soporte para incidentes activos.", "Las updates tienen secretos tecnicos?", "No. Project Pulse muestra progreso sin credenciales, secretos de arquitectura, vulnerabilidades o contexto privado."]]
  }
} satisfies Record<Locale, Record<string, string | string[][]>>;

export const contactLocalized = {
  en: {
    label: "- Contact", navCta: "Email info", heroTitle: "Tell us what is happening. We will help you turn it into a clear next move.", heroBody: "Use the form for product questions, technical problems, security concerns, partnerships, hiring, or anything that needs a steady technical partner. The form opens an email draft to info@saasolution.com with your request.",
    formTitle: "Send a request", name: "Full name", email: "Email", company: "Company", phone: "Phone", topic: "Topic", message: "Request", attachment: "Attachment", attachmentHint: "Select a file here, then attach it to the email draft before sending. Browser mailto forms cannot attach files automatically.", placeholders: ["Jane Doe", "jane@company.com", "Company name", "+34 600 000 000", "What do you need help with?"], topics: ["Product build", "Support request", "Security review", "Hardware integration", "Process improvement", "Partnership"], consent: "By sending, you agree that SaaSolution may contact you about this request.", send: "Open email draft", infoTitle: "Direct contact", phoneTitle: "Phone", emailTitle: "Email", officeTitle: "Offices", mapTitle: "Office map", mapBody: "Current map pins use temporary central office locations in Ceuta, Asuncion, and Cebu City.", peopleTitle: "People you may hear from"
  },
  nl: {
    label: "- Contact", navCta: "Mail info", heroTitle: "Vertel ons wat er speelt. Wij helpen er een duidelijke volgende stap van te maken.", heroBody: "Gebruik het formulier voor productvragen, technische problemen, beveiligingsvragen, partnerships, hiring of alles wat een stabiele technische partner nodig heeft. Het formulier opent een e-mailconcept naar info@saasolution.com met je verzoek.",
    formTitle: "Verzoek versturen", name: "Volledige naam", email: "E-mail", company: "Bedrijf", phone: "Telefoon", topic: "Onderwerp", message: "Verzoek", attachment: "Bijlage", attachmentHint: "Selecteer hier een bestand en voeg het daarna toe aan het e-mailconcept voordat je verzendt. Browsers kunnen bijlagen niet automatisch toevoegen via mailto.", placeholders: ["Jane Doe", "jane@bedrijf.com", "Bedrijfsnaam", "+34 600 000 000", "Waar heb je hulp bij nodig?"], topics: ["Product bouwen", "Supportverzoek", "Beveiligingsreview", "Hardware-integratie", "Procesverbetering", "Partnership"], consent: "Door te verzenden ga je akkoord dat SaaSolution contact mag opnemen over dit verzoek.", send: "Open e-mailconcept", infoTitle: "Direct contact", phoneTitle: "Telefoon", emailTitle: "E-mail", officeTitle: "Kantoren", mapTitle: "Kantorenkaart", mapBody: "De huidige kaartpinnen gebruiken tijdelijke centrale kantoorlocaties in Ceuta, Asuncion en Cebu City.", peopleTitle: "Mensen van wie je kunt horen"
  },
  de: {
    label: "- Kontakt", navCta: "Info mailen", heroTitle: "Erzaehlen Sie uns, was los ist. Wir helfen, daraus den naechsten klaren Schritt zu machen.", heroBody: "Nutzen Sie das Formular fuer Produktfragen, technische Probleme, Sicherheitsthemen, Partnerschaften, Hiring oder alles, was einen verlaesslichen technischen Partner braucht. Das Formular oeffnet einen E-Mail-Entwurf an info@saasolution.com.",
    formTitle: "Anfrage senden", name: "Vollstaendiger Name", email: "E-Mail", company: "Unternehmen", phone: "Telefon", topic: "Thema", message: "Anfrage", attachment: "Anhang", attachmentHint: "Datei hier auswaehlen und danach vor dem Senden an den E-Mail-Entwurf anhaengen. Browser koennen Dateien per mailto nicht automatisch anhaengen.", placeholders: ["Jane Doe", "jane@firma.com", "Unternehmensname", "+34 600 000 000", "Wobei brauchen Sie Hilfe?"], topics: ["Produktbau", "Supportanfrage", "Sicherheitspruefung", "Hardware-Integration", "Prozessverbesserung", "Partnerschaft"], consent: "Mit dem Senden stimmen Sie zu, dass SaaSolution Sie zu dieser Anfrage kontaktieren darf.", send: "E-Mail-Entwurf oeffnen", infoTitle: "Direkter Kontakt", phoneTitle: "Telefon", emailTitle: "E-Mail", officeTitle: "Bueros", mapTitle: "Buerokarte", mapBody: "Die aktuellen Kartenpins nutzen vorlaeufige zentrale Buerostandorte in Ceuta, Asuncion und Cebu City.", peopleTitle: "Personen, von denen Sie hoeren koennen"
  },
  es: {
    label: "- Contacto", navCta: "Enviar email", heroTitle: "Cuentanos que esta pasando. Te ayudamos a convertirlo en un siguiente paso claro.", heroBody: "Usa el formulario para preguntas de producto, problemas tecnicos, seguridad, partnerships, hiring o cualquier tema que necesite un partner tecnico estable. El formulario abre un borrador a info@saasolution.com.",
    formTitle: "Enviar solicitud", name: "Nombre completo", email: "Email", company: "Empresa", phone: "Telefono", topic: "Tema", message: "Solicitud", attachment: "Adjunto", attachmentHint: "Selecciona un archivo aqui y luego adjuntalo al borrador antes de enviar. Los navegadores no pueden adjuntar archivos automaticamente con mailto.", placeholders: ["Jane Doe", "jane@empresa.com", "Nombre de empresa", "+34 600 000 000", "En que necesitas ayuda?"], topics: ["Crear producto", "Solicitud de soporte", "Revision de seguridad", "Integracion hardware", "Mejora de procesos", "Colaboracion"], consent: "Al enviar, aceptas que SaaSolution te contacte sobre esta solicitud.", send: "Abrir borrador", infoTitle: "Contacto directo", phoneTitle: "Telefono", emailTitle: "Email", officeTitle: "Oficinas", mapTitle: "Mapa de oficinas", mapBody: "Los pins actuales usan ubicaciones centrales temporales en Ceuta, Asuncion y Cebu City.", peopleTitle: "Personas que pueden responder"
  }
} satisfies Record<Locale, Record<string, string | string[]>>;

export const contactPeopleLocalized = {
  en: [
    ["Othman El Haddouti", "Founder / Systems Partner", "Hardware, software, security, and process strategy."],
    ["Maya Torres", "Client Operations", "First response, scheduling, and project intake."],
    ["Jonas Vermeer", "Technical Lead", "Architecture, integrations, and delivery planning."]
  ],
  nl: [
    ["Othman El Haddouti", "Oprichter / systeempartner", "Hardware, software, beveiliging en processtrategie."],
    ["Maya Torres", "Klantoperaties", "Eerste reactie, planning en projectintake."],
    ["Jonas Vermeer", "Technisch lead", "Architectuur, integraties en leveringsplanning."]
  ],
  de: [
    ["Othman El Haddouti", "Gruender / Systempartner", "Hardware, Software, Sicherheit und Prozessstrategie."],
    ["Maya Torres", "Kundenoperationen", "Erste Antwort, Terminplanung und Projektaufnahme."],
    ["Jonas Vermeer", "Technischer Lead", "Architektur, Integrationen und Lieferplanung."]
  ],
  es: [
    ["Othman El Haddouti", "Fundador / partner de sistemas", "Hardware, software, seguridad y estrategia de procesos."],
    ["Maya Torres", "Operaciones de cliente", "Primera respuesta, planificacion e intake de proyectos."],
    ["Jonas Vermeer", "Lead tecnico", "Arquitectura, integraciones y planificacion de entrega."]
  ]
} satisfies Record<Locale, string[][]>;
